### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Lz1y** [EgeBalci/Amber#5]
System: Macos mojave
Error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1243e0b]

goroutine 1 [running]:
gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).Finish(0x0)
	/Users/ziyiliu/Documents/Golang/src/gopkg.in/cheggaaa/pb.v1/pb.go:227 +0x3b
main.parseErr(0x13427a0, 0xc00009c500)
	/Users/ziyiliu/Documents/Golang/src/github.com/egebalci/amber/common.go:143 +0xe3
main.banner()
	/Users/ziyiliu/Documents/Golang/src/github.com/egebalci/amber/common.go:208 +0x9d
main.main()
	/Users/ziyiliu/Documents/Golang/src/github.com/egebalci/amber/amber.go:35 +0x483
```

**Comment by Lz1y** [comment]
```golang
func banner() {

	if runtime.GOOS == "windows" {
		print(BasicBanner, "R")
	} else {
		powerlineFonts, err := exec.Command("fc-list").Output()
		parseErr(err)
		if strings.Contains(string(powerlineFonts), "Powerline") {
			print(BANNER, "R")
		} else {
			print(BasicBanner, "R")
		}
	}
	//BoldRed.Print(BANNER)

	BoldBlue.Print("# Version: ")
	BoldGreen.Println(VERSION)
	BoldBlue.Print("# Author: ")
	BoldGreen.Println("Ege BalcÄ±")
	BoldBlue.Print("# Source: ")
	BoldGreen.Println("github.com/egebalci/amber")
}
```

macos haven't this command `fc-list`...

**Comment by EgeBalci** [comment]
It'll be fixed in the next release thanks for pointing out.

**Comment by joker8989** [comment]
I havenot tested it yet but i will according to the member above's error
when the "next release" will be available?

**Comment by EgeBalci** [comment]
In couple of months i hope :)

**Comment by Lz1y** [comment]
Got it!BTW, Awesome project!
